// Generated by gencpp from file aa274_s2/Section6msg.msg
// DO NOT EDIT!


#ifndef AA274_S2_MESSAGE_SECTION6MSG_H
#define AA274_S2_MESSAGE_SECTION6MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aa274_s2
{
template <class ContainerAllocator>
struct Section6msg_
{
  typedef Section6msg_<ContainerAllocator> Type;

  Section6msg_()
    : rho(0.0)
    , delta(0.0)
    , alpha(0.0)  {
    }
  Section6msg_(const ContainerAllocator& _alloc)
    : rho(0.0)
    , delta(0.0)
    , alpha(0.0)  {
  (void)_alloc;
    }



   typedef double _rho_type;
  _rho_type rho;

   typedef double _delta_type;
  _delta_type delta;

   typedef double _alpha_type;
  _alpha_type alpha;





  typedef boost::shared_ptr< ::aa274_s2::Section6msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aa274_s2::Section6msg_<ContainerAllocator> const> ConstPtr;

}; // struct Section6msg_

typedef ::aa274_s2::Section6msg_<std::allocator<void> > Section6msg;

typedef boost::shared_ptr< ::aa274_s2::Section6msg > Section6msgPtr;
typedef boost::shared_ptr< ::aa274_s2::Section6msg const> Section6msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aa274_s2::Section6msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aa274_s2::Section6msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aa274_s2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'aa274_s2': ['/home/aa274/catkin_ws/src/aa274_s2/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aa274_s2::Section6msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aa274_s2::Section6msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aa274_s2::Section6msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aa274_s2::Section6msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aa274_s2::Section6msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aa274_s2::Section6msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aa274_s2::Section6msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "745d32393bd07b7f1c1cd05adaf03d1e";
  }

  static const char* value(const ::aa274_s2::Section6msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x745d32393bd07b7fULL;
  static const uint64_t static_value2 = 0x1c1cd05adaf03d1eULL;
};

template<class ContainerAllocator>
struct DataType< ::aa274_s2::Section6msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa274_s2/Section6msg";
  }

  static const char* value(const ::aa274_s2::Section6msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aa274_s2::Section6msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 rho\n\
float64 delta\n\
float64 alpha\n\
\n\
";
  }

  static const char* value(const ::aa274_s2::Section6msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aa274_s2::Section6msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rho);
      stream.next(m.delta);
      stream.next(m.alpha);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Section6msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aa274_s2::Section6msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aa274_s2::Section6msg_<ContainerAllocator>& v)
  {
    s << indent << "rho: ";
    Printer<double>::stream(s, indent + "  ", v.rho);
    s << indent << "delta: ";
    Printer<double>::stream(s, indent + "  ", v.delta);
    s << indent << "alpha: ";
    Printer<double>::stream(s, indent + "  ", v.alpha);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AA274_S2_MESSAGE_SECTION6MSG_H
